This is makeindex, version 2.15 [TeX Live 2016] (kpathsea + Thai support).
Scanning style file /Users/susana/libro-pasantia/.texpadtmp/thesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file /Users/susana/libro-pasantia/.texpadtmp/thesis.acn...done (0 entries accepted, 0 rejected).
Nothing written in /Users/susana/libro-pasantia/.texpadtmp/thesis.acr.
Transcript written in /Users/susana/libro-pasantia/.texpadtmp/thesis.alg.
